### ISSUE TITLE
How large memory needed?

### ISSUE THREAD

**Issue by Reedwarbler** [ssadedin/bazam#13]
I am trying to use bazam to realign a very large bam (200x) with the following command:
```
java -Xmx45g -jar ${JAR} -bam ${BAM} | \
         bwa mem -p -M -t 8 ${REF}  - | \
         samtools view -bSu - | \
         samtools sort --output-fmt CRAM --reference ${REF} -m 30G -@ 8 -o sorted.cram
```
I set 90G memory with 16 cores, and the job is always killed because of memory issue. I wonder is there something wrong for the command I use? Or I need to set a larger memory? Thank you.

**Comment by Reedwarbler** [comment]
Sorry I think I found the problem, it is the `-m` option in samtools sort. Not the total but per thread maximum memory.

**Comment by ssadedin** [comment]
Ah, good to hear - I was going to say that I have been doing some fine tuning on memory usage and I think that future versions should reduce the memory down quite a bit - but I was thinking what you were seeing still went outside the bounds of my expectations so it's good to hear you found the solution!

**Comment by Reedwarbler** [comment]
Thank you for the reply. After for several hours running, the jobs is killed again because of memory issue. Run with the following command:
```
java -Xmx45g -jar ${JAR} -bam ${BAM} | \
         bwa mem -p -M -t 8 ${REF}  - | \
         samtools view -bSu - | \
         samtools sort --output-fmt CRAM --reference ${REF} -m 5G -@ 8 -o sorted.cram
```
I changed `-m` from 30G to 5G. It works at the beginning. But seems still trigger a large memory (maximum 90G). Any suggestions?

**Comment by ssadedin** [comment]
Would you be willing to give the 1.02 beta version a try? I have pushed several changes that should control memory usage much better. You would need to clone and build from source but should be straight forward I think. (See https://github.com/ssadedin/bazam/tree/1.0.2-beta)

**Comment by Reedwarbler** [comment]
Glad to have a try. Will let you know how it goes.

**Comment by Reedwarbler** [comment]
Got this error when tried to run:
```
git clone git@github.com:ssadedin/bazam.git
cd bazam
git submodule update --init --recursive
**./gradlew clean jar**
```


```
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/tools/bazam/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating root project 'bazam'.
> build/classes/bazam.properties (No such file or directory)
```

**Comment by ssadedin** [comment]
Apologies, that's actually an issue with the build script.

Just do:

```
mkdir -p build/classes
```

and then the build should run using:

```
./gradlew jar
```

**Comment by Reedwarbler** [comment]
It run successfully with the following config:
```
java -Xmx45g -jar ${JAR} -bam ${BAM} | \
         bwa mem -p -M -t 8 ${REF}  - | \
         samtools view -bSu - | \
         samtools sort --output-fmt CRAM --reference ${REF} -m 5G -@ 8 -o sorted.cram
```

I set peak mem: 120G on a slurm cluster. And the final time and memory consuming:
```
       JobID  AllocCPUS      State     ReqMem     MaxRSS    Elapsed  Timelimit    CPUTime    ReqTRES
------------ ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
32282672             16  COMPLETED      120Gn            4-11:00:48 10-05:00:+ 71-08:12:48 cpu=16,me+
32282672.ba+         16  COMPLETED      120Gn 103502528K 4-11:00:48            71-08:12:48
```
Thank you for the help.

**Comment by ssadedin** [comment]
Thought I would just follow up on this. We have been doing more memory profiling and have found that in some cases what is happening is that BWA itself is using significant memory because of the order which it sees the reads. I am implementing some workarounds to try and mitigate this.
