### ISSUE TITLE
Option to emit original quality scores in BQSR-ed BAMs

### ISSUE THREAD

**Issue by wengkhong** [ssadedin/bazam#19]
Hi. First of all, bazam is a really great tool and is saving us a lot of time now that we're realigning our WGS data to hg38. My BAM files have already undergone GATK BQSR, with original quality scores stored under the 'OQ' tag. I was wondering if it would be possible to add an option to bazam to use quality scores from the OQ tag when generating FASTQs. This would allow us to faithfully reproduce the original raw FASTQ files when realigning.

**Comment by ssadedin** [comment]
That definitely sounds like a useful option - I will look at adding this in the near future.

Thanks for the suggestion!

**Comment by ssadedin** [comment]
I have added some support for this in https://github.com/ssadedin/bazam/commit/e9657f74067a686c952c54a085923b710630c8b9 which is on the [1.0.2-beta](https://github.com/ssadedin/bazam/tree/1.0.2-beta) branch. Would be great if you can give it a test? You would run it like:

```
java -jar build/libs/bazam.jar -bqtag OQ your.bam ....
```

**Comment by wengkhong** [comment]
Hi Simon. We fetched the 1.0.2-beta branch, built and tested it. We can confirm that it works as expected. Thanks for addressing this feature suggestion so quickly! Best wishes, WK

**Comment by ssadedin** [comment]
Great to hear it works - thanks for testing it out!
