### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by tseemann** [ssadedin/bazam#4]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/linuxbrew/.linuxbrew/Cellar/bazam/1.0.1/libexec/bazam.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by sjackman** [comment]
Yes, please.

**Comment by ssadedin** [comment]
Thanks for mentioning this - I always forget to test with Java 9!

Unfortunately it's a side effect of some compatibility issues between the Groovy in use under the hood and Java 9.  I have pushed a workaround that works on most JDK's but may not work universally. For now, other than using JDK8 or adding exotic command line options when running, it's the best that can be done.  

The warnings don't do any harm though, so other than offending your eyeballs everything should work fine even if the workaround I added does not suppress the warnings.

**Comment by sjackman** [comment]
Thanks for the response, Simon. I've had trouble with other tools with Java 9 as well. I think I'll downgrade the default Java interpreter on my system to Java 8.

**Comment by ssadedin** [comment]
Closing for now, I think this is resolved on most JDKs and there is not much else to do.

Thanks!

**Comment by sjackman** [comment]
I think we're up to Java 11 now! http://openjdk.java.net/projects/jdk/11/

**Comment by tseemann** [comment]
@ssadedin stop using groovy please :)

**Comment by ssadedin** [comment]
Indeed :-) Fortunately the workaround I have applied still works in JDK11 for the distributions most in use (OpenJDK, Oracle, etc).
