### ISSUE TITLE
how to run on CRAM

### ISSUE THREAD

**Issue by brentp** [ssadedin/bazam#8]
when I run on cram I get an error message including:
```
Exception in thread "main" java.lang.IllegalStateException: A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download
```
how/where can I set this from the command-line?

**Comment by ssadedin** [comment]
Bazam is using the underlying HTSJDK libraries, so you can inform it about how to locate the reference using the standard properties that HTSJDK supports. The most simple way is to directly specify it using the `samjdk.reference_fasta` property, eg:

```
java  -Xmx8g -Dsamjdk.reference_fasta=/reference/hg38/Homo_sapiens_assembly38.fasta -jar build/libs/bazam.jar test.cram > test.fastq.gz
```
Thanks for mentioning as this is not well documented!

**Comment by brentp** [comment]
thanks!

**Comment by ssadedin** [comment]
Closing now that this is documented in the main README.
